name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 26.1
          - 26.3
          - 27.1
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v2
    - name: Byte compile
      run: |
        emacs -Q --batch --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile cos5.el
    - name: Run tests
      run: |
        emacs -Q --batch -L . -l  cos5-tests -f ert-run-tests-batch-and-exit
